---
title: "Lymphoid Analysis"
format: html
editor: visual
---

This notebook includes the code used to generate Figure 2 and Supplementary Figures 2-4.

```{bash, eval=FALSE}
qsub recluster_lymphoid.sh
```

```{r ReadData}
lymphoid <- 
  readRDS(paste0(data_dir,
          "lymphoid_subset_reintegrated_harmony_noAbema3_diet.rds"))
```

```{r LabelCells}
# add cell type labels to clusters
ids <- 
  read.delim(paste0(dir,"meta/lymphoid_cluster_ids.csv"),
             header = TRUE,
             sep = ",",
             as.is = T)
ids$cluster_marker_celltype <-
  ifelse(str_detect(ids$cell_type, "Unassigned"),
         paste0(ids$cluster, ":", ids$marker, " ", ids$cell_type),
         paste0(ids$cluster, ":", ids$marker, "+ ", ids$cell_type))

# add cluster_marker_celltype
anno <- 
  ids$cluster_marker_celltype
Idents(lymphoid) <- 
  "seurat_clusters"
names(anno) <- 
  levels(lymphoid)
lymphoid <- 
  RenameIdents(lymphoid, anno)
lymphoid$cluster_marker_celltype <- 
  Idents(lymphoid)

# add cluster_marker_celltype
ids$cluster_celltype <-
  paste0(ids$cluster, ": ", ids$cell_type)
anno <- 
  ids$cluster_celltype
Idents(lymphoid) <- 
  "seurat_clusters"
names(anno) <- 
  levels(lymphoid)
lymphoid <- 
  RenameIdents(lymphoid, anno)
lymphoid$cluster_celltype <- 
  Idents(lymphoid)

# save object
saveRDS(lymphoid,
        paste0(dir,"/objects/lymphoid_subset_reintegrated_harmony_diet.rds"))
```

```{r SetCellColors}
# set colors for celltypes
cl_colors <- 
  c("#0166d8","#ec102f","#3aa609","#6524ff","#f8d147",
    "#5ce8ef","#fd6ca0","#476ba5","#fea27a","#add465",
    "#b775e1","#fe8f06","#5cfdc4","#feafda","#00228b", 
    "#fd5925","#166d2a","#a90aa1","#f3c011","#5ac7dc")
Idents(lymphoid) <- "seurat_clusters"
names(cl_colors) <- levels(lymphoid)

# set colors for celltypes
ct_colors <- 
  c("#0166d8","#ec102f","#3aa609","#6524ff","#f8d147",
    "#5ce8ef","#fd6ca0","#476ba5","#fea27a","#add465",
    "#b775e1","#fe8f06","#5cfdc4","#feafda","#00228b", 
    "#fd5925","#166d2a","#a90aa1","#f3c011","#5ac7dc")
Idents(lymphoid) <- "cluster_marker_celltype"
names(ct_colors) <- levels(lymphoid)
```

```{r Fig2A}
# make UMAP labeled by cluster
DimPlot(lymphoid,
        group.by = "seurat_clusters",
        raster = F,
        label = T,
        label.box = T,
        repel = T,
        label.size = 3,
        cols = cl_colors) &
  xlab("UMAP_1") &
  ylab("UMAP_2") &
  ggtitle("Seurat Clusters") &
  guides(color = "none")
ggsave(filename = paste0(fig_dir,"lymphoid_umap_colored_by_cluster.jpeg"),
       width = 6,
       height = 4.5)

# All data colored by cluster_marker_celltype with bottom legend
DimPlot(lymphoid,
        group.by = "cluster_marker_celltype",
        raster = F,
        cols = ct_colors) &
  xlab("UMAP_1") &
  ylab("UMAP_2") &
  ggtitle("Cluster: Cell Type") &
  theme(legend.position = "bottom",
        legend.justification = "center") &
  guides(color = guide_legend(ncol = 3,
                              override.aes = list(size=3)))
ggsave(filename = paste0(fig_dir,"lymphoid_umap_colored_by_cluster_marker_celltype_bottom_legend.jpeg"),
       width = 9.2,
       height = 9)
```

```{r SuppFig2A}
# make UMAP faceted by time and site
DimPlot(lymphoid,
        group.by = "cluster_marker_celltype",
        raster = F,
        pt.size = 0.6,
        cols = ct_colors) &
  xlab("UMAP_1") &
  ylab("UMAP_2") &
  ggtitle("Cluster: Cell Type")  &
  facet_grid(rows = vars(lymphoid$Time),
             cols = vars(lymphoid$site)) &
  theme(text = element_text(size = 12),
        strip.background = element_rect(colour = "black", 
                                        fill = "white"),
        legend.position = "bottom",
        legend.justification = "center") &
  guides(color = guide_legend(ncol = 5,
                              override.aes = list(size=3)))
ggsave(filename = paste0(fig_dir, "lymphoid_umap_colored_by_cluster_marker_celltype_split_by_site_and_time.jpeg"),
       width = 15,
       height = 7)
```

```{r SuppFig2B}
# make feature plots with canonical lymphoid markers
Idents(lymphoid) <- "seurat_clusters"
p <-
  FeaturePlot(lymphoid,
              features = c("CD3E","CD4","CD8A","NCAM1",
                           "CD69","GZMA","IFNG","PDCD1",
                           "TIGIT","FOXP3","CD19","SDC1"),
              order = T,
              raster = F,
              max.cutoff = 3.5,
              label = F,
              label.color = "black",
              ncol = 4,
              pt.size = 0.2) &
  scale_color_continuous(type = "viridis")
p + plot_layout(guides = "collect")
ggsave(filename = paste0(fig_dir, "lymphoid_marker_featureplots.jpeg"),
       width = 13.5,
       height = 11)

```

```{r SuppFig3A}
# make feature plots with abemaciclib targets at T1 and T2
Idents(lymphoid) <- "seurat_clusters"
p <-
  FeaturePlot(lymphoid,
              split.by = "Time",
              features = c("CDK4","CDK6","CDK2"),
              order = T,
              raster = F,
              max.cutoff = 2.5,
              pt.size = 0.2) &
  scale_color_continuous(type = "viridis") 
p + plot_layout(guides = "collect")
ggsave(filename = paste0(fig_dir, "lymphoid_abema_targets_featureplots_split_by_time.jpeg"),
       width = 8.5,
       height = 10)


Idents(lymphoid) <- "seurat_clusters"
p <-
  FeaturePlot(lymphoid,
              features = c("CDK4","CDK6","CDK2"),
              order = T,
              raster = F,
              max.cutoff = 2.5,
              pt.size = 0.2) &
  scale_color_continuous(type = "viridis")
p + plot_layout(guides = "collect")
ggsave(filename = paste0(fig_dir, "lymphoid_abema_targets_featureplots.jpeg"),
       width = 8,
       height = 8)
```

```{r SuppFig3B}
# make feature plots with hormone receptors at T1 and T2
Idents(lymphoid) <- "seurat_clusters"
p <-
  FeaturePlot(lymphoid,
              split.by = "Time",
              features = c("ESR1","ESR2","GPER1","PGR","AR"),
              order = T,
              raster = F,
              max.cutoff = 2,
              pt.size = 0.2) &
  scale_color_continuous(type = "viridis") 
p + plot_layout(guides = "collect")
ggsave(filename = paste0(fig_dir, "lymphoid_et_targets_featureplots_split_by_time.jpeg"),
       width = 8.5,
       height = 15)


Idents(lymphoid) <- "seurat_clusters"
p <-
  FeaturePlot(lymphoid,
              features = c("ESR1","ESR2","GPER1","PGR","AR"),
              order = T,
              raster = F,
              max.cutoff = 2,
              pt.size = 0.2) &
  scale_color_continuous(type = "viridis")
p + plot_layout(guides = "collect")
ggsave(filename = paste0(fig_dir, "lymphoid_et_targets_featureplots.jpeg"),
       width = 8,
       height = 8)
```

```{r FindAllMarkers}
# find all markers and save table
Idents(lymphoid) <- "cluster_marker_celltype"
markers <- 
  FindAllMarkers(lymphoid,
                 only.pos = T,
                 assay = "RNA")
markers <- 
  markers %>%
  filter(p_val_adj <= 0.05)
markers$cluster <-
  gsub("Naïve", "Naive", markers$cluster)
write.csv(markers,
          paste0(tbl_dir, "lymphoid_find_all_markers.csv"),
          row.names = F,
          quote = F)

top_markers <- 
  markers %>%
  group_by(cluster) %>%
  slice_min(p_val_adj, 
            n = 100) %>%
  slice_max(avg_log2FC, n = 50) %>%
  as.data.frame()
write.csv(top_markers,
          paste0(tbl_dir, "lymphoid_top50_find_all_markers.csv"),
          row.names = F,
          quote = F)
```

```{r Fig2B}
# make dot plot of top marker genes per cluster
genes <-
  list("0:IL7R+ Naïve T-cells" = c("IL7R","TNFAIP3","CCR7"),
       "1:CCL5+ Cytotoxic T-cells" = c("CCL5","GZMK","CD8A"),
       "2:PRF1+ Cytotoxic NK cells" = c("PRF1","FCGR3A","GNLY"),
       "3:FCER2+ B-cells" = c("FCER2","HLA-DRA","CD83"),
       "4:IFNG+ Activated T-cells" = c("IFNG","CCL4","TNFSF9"),
       "5:CD44+ T-cells" = c("CD44","NEAT1","PLCG2"),
       "6:FOXP3+ Tregs" = c("FOXP3","IL2RA","CTLA4"),
       "7:AREG+ NK cells" = c("AREG","NCR1","NCAM1"),
       "8:IGHG1+ Plasma Cell" = c("IGHG1","IGHG4","PRDX4"),
       "9: Unassigned 1" = c("C1QA","C1QB","LYZ"),
       "10:CD69+ Activated T-cells" = c("CD69","JUN","FOS"),
       "11:IGHM+ Plasma Cell" = c("IGHM","DERL3","IGLC1"),
       "12:IGHA1+ Plasma Cell" = c("IGHA1","TNFRSF17","IGHD"),
       "13: Unassigned 2" = c("CXCL2","IGFBP5","PIP"),
       "14:IFIT1+ T-cells" = c("IFIT1","IRF7","STAT1"),
       "15:TNFRSF13B+ B cells" = c("TNFRSF13B","HLA-DQA1","HLA-DRB1"),
       "16:TIGIT+ Exhausted T-cells" = c("TIGIT","PDCD1","TOX"),
       "17:IGLC2+ Plasma Cell" = c("IGLC2","IGLC3","IGHG3"),
       "18: Unassigned 3" = c("NFKBIZ","FOSB","NFKBIA"),
       "19: Unassigned 4" = c("MS4A2","TPSAB1","CTSG"))
genes <-
  genes %>%
  unlist() %>%
  as.character()
DotPlot(lymphoid,
        group.by = "seurat_clusters",
        features = genes,
        col.min = -1,
        col.max = 3) &
  scale_color_continuous(type = "viridis") &
  ylab("Cluster") &
  theme(axis.text.x=element_text(angle=90, hjust=1),
        legend.position = "top",
        legend.justification = "center") 
ggsave(filename = paste0(fig_dir,"lymphoid_cluster_marker_celltype_marker_dotplot.jpeg"),
       width = 12,
       height = 6)
```

```{r Fig2C}
# make pathway plots with consistent scale
# reduce information in meta data
obj <- lymphoid
obj@meta.data <-
  obj@meta.data[,c("cluster_marker_celltype", "Time")]

# set up pathways 
go_bp <- msigdbr(species = "Homo sapiens",
                category = "C5",
                subcategory = "GO:BP") %>% 
  split(x = .$gene_symbol,
        f = .$gs_name)
hallmark <- msigdbr(species = "Homo sapiens",
                category = "H")  %>% 
  split(x = .$gene_symbol,
        f = .$gs_name)
kegg <- 
  msigdbr(species = "Homo sapiens",
          category = "C2",
          subcategory = "CP:KEGG") %>% 
                split(x = .$gene_symbol,
                      f = .$gs_name)
genesets <- 
  c(go_bp,hallmark, kegg)

# read in pathway csv
p <-
  read.csv("~/projects/240320_abemaimmune/pathways.csv")
all(p$pathway %in% names(genesets)) # TRUE

# select only pathways of interest
pathways <-
  genesets[unique(p$pathway)]

# make sure we only have each gene once!
for (p in names(pathways)){
  pathways[[p]] <-
    pathways[[p]] %>% unique()
}

# save as a data frame
pathway_genes <-
  stack(pathways)
colnames(pathway_genes) <-
  c("gene", "pathway")
write.csv(pathway_genes,
          paste0(tbl_dir,
                 "pathway_genes.csv"),
          row.names = F,
          quote = F)
  
# make a module score for each pathway
obj <- 
  AddModuleScore(obj,
                 pathways,
                 name = names(pathways))

# rename columns so they are the pathways
colnames(obj@meta.data)[3:ncol(obj@meta.data)] <-
  names(pathways)

# calculate mean expression of each module at T1 and T2
expr <-
  obj@meta.data %>%
  group_by(Time, cluster_marker_celltype) %>%
  summarise(across(HALLMARK_ALLOGRAFT_REJECTION:GOBP_POSITIVE_REGULATION_OF_NK_T_CELL_ACTIVATION, 
                   ~ mean(.x, na.rm = T))) %>%
  pivot_longer(cols = 3:ncol(obj@meta.data),
               names_to = "signature",
               values_to = "mean_expr")

# statistics 
stats <-
  expr %>%
  dplyr::select(cluster_marker_celltype, signature) %>%
  distinct() %>%
  as.data.frame()
stats$pvalue <-
  "NA"
for (c in unique(stats$cluster_marker_celltype)){
  for (p in unique(stats$signature)){
    tryCatch({
    sub <-
      obj@meta.data %>%
      filter(cluster_marker_celltype == c)
    sub <- 
      sub[,c(p, "Time")]
    test <-
      wilcox.test(sub[,1] ~ sub[,2])
    stats[stats$cluster_marker_celltype == c & stats$signature == p, "pvalue"] <-
      test$p.value
    }, error = function(e) {print(paste("cluster", c, "not enough cells"))})
  }
}
stats$FDR <-
  p.adjust(stats$pvalue,
           method = "BH")
write.table(stats,
            paste0(tbl_dir, "lymphoid_all_patients_pathway_stats.csv"),
            sep = ",",
            row.names = F,
            quote = F)

stats[stats$cluster_marker_celltype == "19: Unassigned 4", "FDR"] <- 1

# add asterisk
stats$sig <- ""
for (i in 1:nrow(stats)) {
  if (stats[i,"FDR"] > 0.05) {
    stats[i,"sig"] <- ""
  } else if (stats[i,"FDR"] <= 0.0001) {
    stats[i,"sig"] <- "****"
  } else if (stats[i,"FDR"] <= 0.001) {
    stats[i,"sig"] <- "***"
  } else if (stats[i,"FDR"] <= 0.01) {
    stats[i,"sig"] <- "**"
  } else if (stats[i,"FDR"] <= 0.05) {
    stats[i,"sig"] <- "*"
  }
}

for (i in 1:nrow(stats)){
  ct <- 
    stats[i, "cluster_marker_celltype"]
  p <- 
    stats[i, "signature"]
  expr[expr$cluster_marker_celltype == ct &
         expr$signature == p &
         expr$Time == "T2", "pvalue"] <-
    stats[i, "pvalue"]
  expr[expr$cluster_marker_celltype == ct &
         expr$signature == p &
         expr$Time == "T2", "FDR"] <-
    stats[i, "FDR"]
  expr[expr$cluster_marker_celltype == ct &
         expr$signature == p &
         expr$Time == "T2", "sig"] <-
    stats[i, "sig"]
}

write.table(expr,
            paste0(tbl_dir, "lymphoid_all_patients_pathway_expr_stats.csv"),
            sep = ",",
            row.names = F,
            quote = F)

# center scale at 0
for (p in unique(expr$signature)){
  sub <-
    expr %>%
    filter(signature == p)
  min <-
    ifelse(min(sub$mean_expr) > 0,
           0, min(sub$mean_expr))
  plot <-
    sub  %>%
    ggplot(aes(x = Time,
               y = cluster_marker_celltype,
               fill = mean_expr)) +
    geom_tile() +
    scale_fill_gradient2(low="blue", 
                         mid = "grey95",
                         high="red", 
                         na.value = "white",
                         midpoint = 0,
                         limits = c(min, max(sub$mean_expr)),
                         name = "Mean Module\nExpression",
                         labels = label_number(accuracy = 0.01)) +
    scale_y_discrete(expand = expand_scale(mult = c(0, 0))) +
    scale_x_discrete(expand = expand_scale(mult = c(0, 0)),
                     position = "top") +
    geom_text(data = sub,
              aes(label = sig),
              colour = "black",
              size = 10/.pt,
              vjust = 0.5,
              hjust = 0.5) +
    theme_bw() +
    xlab(NULL) +
    ylab(NULL) +
    coord_fixed(ratio = 0.25) +
    ggtitle(gsub("_", " ", p) %>%
              str_wrap(width = 30)) +
    theme(strip.background = element_rect(color = "black",
                                          fill = "white"),
          strip.placement = "outside",
          panel.spacing = unit(5,"pt"),
          plot.title = element_text(hjust = 0.5,
                                    face = "bold",
                                    size = 11),
          legend.position = "bottom",
          legend.key.height = unit(3, "mm"),
          legend.key.width =  unit(1, "cm"),
          legend.title.position = "top",
          legend.title = element_text(hjust = 0.5, size = 10),
          panel.grid.major = element_line(colour = "white"))
  ggsave(plot,
         filename = paste0(fig_dir, "pathway_mid0/lymphoid_all_patients_", str_to_lower(p),"_heatmap.jpeg"),
         height = 4.5,
         width = 6)
}

# center scale at median expression
for (p in unique(expr$signature)){
  sub <-
    expr %>%
    filter(signature == p)
  plot <-
    sub  %>%
    ggplot(aes(x = Time,
               y = cluster_marker_celltype,
               fill = mean_expr)) +
    geom_tile() +
    scale_fill_gradient2(low="blue", 
                         mid = "grey95",
                         high="red", 
                         na.value = "white",
                         midpoint = median(sub$mean_expr),
                         name = "Mean Module\nExpression") +
    scale_y_discrete(expand = expand_scale(mult = c(0, 0))) +
    scale_x_discrete(expand = expand_scale(mult = c(0, 0)),
                     position = "top") +
    geom_text(data = sub,
              aes(label = sig),
              colour = "black",
              size = 10/.pt,
              vjust = 0.5,
              hjust = 0.5) +
    theme_bw() +
    xlab(NULL) +
    ylab(NULL) +
    coord_fixed(ratio = 0.25) +
    ggtitle(gsub("_", " ", p) %>%
              str_wrap(width = 30)) +
    theme(strip.background = element_rect(color = "black",
                                          fill = "white"),
          strip.placement = "outside",
          panel.spacing = unit(5,"pt"),
          plot.title = element_text(hjust = 0.5,
                                    face = "bold",
                                    size = 11),
          legend.position = "bottom",
          legend.key.height = unit(3, "mm"),
          legend.key.width =  unit(1, "cm"),
          legend.title.position = "top",
          legend.title = element_text(hjust = 0.5, size = 10),
          panel.grid.major = element_line(colour = "white"))
  ggsave(plot,
         filename = paste0(fig_dir, "pathway_midMedian/lymphoid_all_patients_", str_to_lower(p),"_heatmap.jpeg"),
         height = 4.5,
         width = 6)
}
```

```{r Fig2D}
# make a violin plot with interferon expression in T-cell clusters
tcells <-
  unique(lymphoid$cluster_marker_celltype)[grep("T-cells", unique(lymphoid$cluster_marker_celltype))]
VlnPlot(subset(lymphoid,
               cluster_marker_celltype %in% tcells),
        features = "IFNG",
        group.by = "cluster_marker_celltype",
        split.by = "Time",
        cols = two,
        alpha = 0.3) &
  xlab(NULL) &
  theme(legend.position = "bottom",
        legend.justification = "center") &
  stat_summary(fun = "mean",
               geom = "crossbar",
               width = 0.4,
               position = position_dodge(width = 0.9),
               linewidth = 0.5,
               color = "#31d800",
               show.legend = F)
ggsave(filename = paste0(fig_dir, "lymphoid_tcell_ifng_violinplot.jpeg"),
       width = 7.2,
       height = 6)

# perform stats on IFNG expression
ifng <-
  lymphoid@assays$RNA@data["IFNG",] %>%
  as.data.frame()
colnames(ifng) <- "IFNG"
all(rownames(ifng) == rownames(lymphoid@meta.data))
ifng <-
  cbind(ifng, lymphoid@meta.data[,c("Time","cluster_marker_celltype")]) %>%
  filter(cluster_marker_celltype %in% tcells)


stats <- data.frame()
for (c in unique(ifng$cluster_marker_celltype)){
  t1 <-
   ifng[ifng$Time == "T1" & ifng$cluster_marker_celltype == c, "IFNG"]
  t2 <-
    ifng[ifng$Time == "T2" & ifng$cluster_marker_celltype == c, "IFNG"]
  pval <-
    wilcox.test(t1, t2)
  stats <- 
    rbind(stats, c(c, mean(t1), mean(t2), pval$p.value))
}
colnames(stats) <-
  c("cluster_marker_celltype","T1_mean", "T2_mean", "pval")
stats$FDR <-
  p.adjust(stats$pval, "BH")
write.csv(stats,
          paste0(fig_dir, "lymphoid_tcell_ifng_violinplot.csv"),
          row.names = F,
          quote = F) 

# pseudobulk IFNG expression in T-cell clusters per patient and timepoint
tc <- 
  subset(lymphoid,
               cluster_marker_celltype %in% tcells)
tc$group <-
  paste0(paste0(tc$orig.ident), "_", 
         gsub("\\+ ", " ", gsub("\\:", " ", tc$cluster_marker_celltype)))
ifng <-
  AggregateExpression(tc,
                      assays = "RNA",
                      features = "IFNG",
                      return.seurat = F,
                      group.by = c("group")) %>%
  as.data.frame() %>%
  t() %>% 
  as.data.frame()
ifng$group <- rownames(ifng)
rownames(ifng) <- NULL
colnames(ifng) <- c("IFNG", "group")
ifng$group <- gsub("RNA.", "", ifng$group)
ifng$patient <-
  str_split_fixed(ifng$group,"\\.", 3)[,1]
ifng$time <-
  str_split_fixed(ifng$group,"\\.", 3)[,2]
ifng$cluster_marker_celltype <-
  str_split_fixed(ifng$group,"\\.", 3)[,3] %>%
  gsub("\\.", " ", .)
ifng$cluster <-
  str_split_fixed(ifng$cluster_marker_celltype, " ", 3)[,1]
ifng$marker <-
  str_split_fixed(ifng$cluster_marker_celltype, " ", 3)[,2]
ifng$celltype <-
  str_split_fixed(ifng$cluster_marker_celltype, " ", 3)[,3]
ifng$cluster_marker_celltype <-
  paste0(ifng$cluster, ":",
         ifng$marker, "+ ",
         ifng$celltype)

ggplot(ifng,
       aes(x = cluster_marker_celltype,
           y = IFNG,
           fill = time)) +
  geom_violin()  +
  geom_point(position = position_jitterdodge(dodge.width = 0.95,
                                             jitter.width = 0.2),
             alpha = 0.4,
             size = 0.7) +
  scale_fill_manual(values = two,
                    name = "Time") +
  theme_cowplot() +
  xlab(NULL) +
  ylab("Normalized Average Expression") +
  ggtitle("IFNG") +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1,
                                   vjust = 1),
        plot.title = element_text(hjust = 0.5))
ggsave(filename = paste0(fig_dir, "lymphoid_tcell_ifng_violinplot_pseudobulk.jpeg"),
       width = 8,
       height = 6)

# make dotplot with interferon response genes in T-cells split between T1 and T2
genes <- c("IFNG","STAT1","STAT2","IRF2","IRF6","IRF9","NLRC5")
# get expresssion data from T-cell object
df <-
  GetAssayData(tc,
               assay = "RNA",
               slot = "data") %>%
  as.data.frame()
df <-
  df[genes,] %>%
  t() %>%
  as.data.frame()
# calculate median signature
signatures <-
  tc@meta.data[,c("Time","cluster_marker_celltype")]
all(rownames(signatures) == rownames(df))
signatures <-
  cbind(signatures, df)
expr <-
  signatures %>%
  group_by(Time, cluster_marker_celltype) %>%
  summarise(across(`IFNG`:`NLRC5`, 
                   ~ mean(.x, na.rm = T))) %>%
  pivot_longer(cols = 3:ncol(signatures),
               names_to = "gene",
               values_to = "mean_expr")
for (t in c("T1", "T2")){
  for (c in unique(expr$cluster_marker_celltype)){
    cc <-
      signatures %>%
      filter(Time == t &
               cluster_marker_celltype == c)
    for (g in unique(expr$gene)){
      expr[expr$Time == t &
             expr$cluster_marker_celltype == c &
             expr$gene == g,
           "pct_expr"] <-
        sum(cc[,g] > 0) / nrow(cc) *100
    }
  }
}
# order genes
expr$gene <-
  factor(expr$gene,
         levels = genes)
# plot
expr %>%
  filter(cluster_marker_celltype %in% tcells) %>%
  ggplot(aes(x = Time,
             y = cluster_marker_celltype,
             color = mean_expr,
             size = pct_expr)) +
  geom_point() +
  facet_grid(cols = vars(gene)) +
  scale_color_continuous(type = "viridis",
                        name = "Mean\nExpression",
                        limits = c(0,1.7),
                        breaks = seq(0,1.5, by = 0.5),
                        na.value = "#FDE725FF") +
  scale_x_discrete(position = "top") +
  scale_size_continuous(name = "%\nExpression") +
  theme_bw() +
  xlab("") +
  ylab("") +
  theme(strip.background = element_rect(color = "black",
                                        fill = "white"),
        strip.placement = "outside",
        panel.spacing = unit(5,"pt"),
        plot.title = element_text(hjust = 0.5,
                                  face = "bold"),
        panel.grid.major = element_line(colour = "white")) 
ggsave(filename = paste0(fig_dir, "lymphoid_interferon_response_dotplot.jpeg"),
       height = 4.25,
       width = 9)

# make a violin plot of a module score of interferon response genes between T1 and T2
genes <- c("STAT1", "STAT2", "IRF2", "IRF6","IRF9", "NLRC5")
tc <-
  AddModuleScore(tc,
                 features = list("IFN_Response" = genes),
                 name = "IFN_Response")
VlnPlot(tc,
        features = c("IFN_Response1"),
        group.by = "cluster_marker_celltype",
        split.by = "Time",
        cols = two,
        pt.size = 0) &
  xlab(NULL) &
  ylab("Module Score") &
  ggtitle("Interferon Response Genes") &
  geom_boxplot(outliers = F,
               width = 0.25,
               position = position_dodge(width = 1)) &
  theme(plot.title = element_text(hjust = 0.5))
ggsave(filename = paste0(fig_dir, "lymphoid_interferon_response_module_violinplot.jpeg"),
       height = 6,
       width = 7)
```

```{r Fig2E_F}
# make trend plots in all data
# set colors
patients <- 
  c("#FFC107", "#449AE4", "#78B389", "#B32357", "#e13219", "#14C7BA", "#871C9A",
    "#FD8305", "#3B3EDE", "#E884AF", "#285d28", "#afc6fe", "#aedfca", "#2C2E9C")
names(patients) <- 
  c("Abema4","Abema5","Abema7","Abema8","Abema9",
    "Abema10","Abema11","Abema12","Abema13","Abema14",
    "Abema15","Abema16","Abema17")

# make proportion table
percent_per_cluster <- 
  prop.table(table(lymphoid$cluster_marker_celltype, 
                   lymphoid$orig.ident), 
             margin = 2) %>%
  as.data.frame() %>%
  rename("Cluster" = "Var1",
         "Sample" = "Var2",
         "Percent" = "Freq") %>%
  mutate(Percent = Percent*100,
         Patient = str_split_fixed(Sample, "_", 2)[,1],
         Time = str_split_fixed(Sample, "_", 2)[,2]) 
write.csv(percent_per_cluster, 
          paste0(fig_dir,"/lymphoid_percent_per_cluster_marker_celltype.csv"))

# use wilcoxon signed-rank test since we are comparing timepoints from the same samples
find_stat <- function(cells, df){
  frequencies <- df[df$Cluster == cells,]
  stats <- wilcox.test(Percent ~ Time,
                       data = frequencies,
                       paired = TRUE)
  p.value <- stats$p.value
  return(p.value)
}
  
find_trend <- function(cells, df){
  frequencies <- 
    df[df$Cluster == cells,]
  frequencies$Patient <-
    factor(frequencies$Patient,
           levels = names(patients))
  # use wilcoxon signed-rank test since we are comparing timepoints from the same samples
  stats <- wilcox.test(Percent ~ Time,
                       data = frequencies,
                       paired = TRUE)
  p.value <- stats$p.value
  plot <- 
    ggplot(data = frequencies,
           aes(x = Time,
               y = Percent,
               group = Patient,
               color = Patient)) +
    labs(title = str_wrap(paste0(cells), width = 30),
         subtitle = paste("p = ", round(p.value, digits = 5))) +
    geom_line() +
    geom_point() +
    theme_bw() +
    scale_color_manual(values = patients) +
    xlab("Timepoint") +
    ylab("% Lymphoid Cells") +
    ylim(0,NA) +
    scale_x_discrete(expand = c(0.1,0.1)) +
    theme(text = element_text(size = 12),
          plot.subtitle = element_text(size = 9,
                                       hjust = 0.5),
          plot.title = element_text(hjust = 0.5,
                                    face = "bold"))
  return(plot)
}

# T1 vs. T2 (all samples)
for (cells in unique(percent_per_cluster$Cluster)) {
  plot <- find_trend(cells, percent_per_cluster)
  stat <- find_stat(cells, percent_per_cluster)
  cells <- gsub(" ", "_", cells) %>%
    gsub("\\:", "", .) %>%
    gsub("\\+", "", .)
  if (stat <= 0.05) {
    filename <- paste0(fig_dir, "trend_significant/lymphoid_all_samples_cluster_",cells,".jpeg")
    } else {
      filename <- paste0(fig_dir, "trend_nonsignificant/lymphoid_all_samples_cluster_",cells,".jpeg")
      }
  ggsave(plot,
         filename = filename,
         width = 4,
         height = 4)
}

# T1 vs. T2 (< 6 months)
less <-
  lymphoid@meta.data[lymphoid@meta.data$abema_duration_v2 == "< 6 months", "patientID"] %>% 
  unique()
pcp <-
  percent_per_cluster %>%
  filter(Patient %in% less) %>%
  filter(Cluster != "19:Unassingned 4")
for (cells in unique(pcp$Cluster)) {
  plot <- find_trend(cells, pcp)
  stat <- find_stat(cells, pcp)
  cells <- gsub(" ", "_", cells) %>%
    gsub("\\:", "", .) %>%
    gsub("\\+", "", .)
  if (stat <= 0.05) {
    filename <- paste0(fig_dir, "trend_significant/lymphoid_less_than_6mo_cluster_",cells,".jpeg")
    } else {
      filename <- paste0(fig_dir, "trend_nonsignificant/lymphoid_less_than_6mo_cluster_",cells,".jpeg")
      }
  ggsave(plot,
         filename = filename,
         width = 4,
         height = 4)
}

# T1 vs. T2 (> 6 months)
greater <-
  lymphoid@meta.data[lymphoid@meta.data$abema_duration_v2 == "> 6 months", "patientID"] %>% 
  unique()
pcp <-
  percent_per_cluster %>%
  filter(Patient %in% greater)
for (cells in unique(pcp$Cluster)) {
  plot <- find_trend(cells, pcp)
  stat <- find_stat(cells, pcp)
  cells <- gsub(" ", "_", cells) %>%
    gsub("\\:", "", .) %>%
    gsub("\\+", "", .)
  if (stat <= 0.05) {
    filename <- paste0(fig_dir, "trend_significant/lymphoid_greater_than_6mo_cluster_",cells,".jpeg")
    } else {
      filename <- paste0(fig_dir, "trend_nonsignificant/lymphoid_greater_than_6mo_cluster_",cells,".jpeg")
      }
  ggsave(plot,
         filename = filename,
         width = 4,
         height = 4)
}



# look at different sites for Tregs
sites <-
  lymphoid@meta.data[,c("patientID","site")]
rownames(sites) <- NULL
sites <-
  distinct(sites)
pcp <-
  merge(x = percent_per_cluster,
        y = sites,
        by.x = "Patient",
        by.y = "patientID")

liver <-
  find_trend(cells, 
             pcp[pcp$site == "liver",])
ln <-
  find_trend(cells, 
             pcp[pcp$site == "lymph_node",])
bone <-
  find_trend(cells, 
             pcp[pcp$site == "bone",])
breast <-
  find_trend(cells, 
             pcp[pcp$site == "breast",])

(liver + ln) / (bone + breast)
```
